// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb add_format [options] id ebook_file
//
// Description:
// Add the e-book in ebook_file to the available formats for the logical book identified by id. You can get id by using the search command. If the format already exists, it is replaced, unless the do not replace option is specified.

package calibredb

type AddFormatOptions struct {
	// Command Line Arguments
	Id        string `validate:"required"`
	EbookFile string `validate:"required"`

	// Command Line Options
	AsExtraDataFile *bool // Add the file as an extra data file to the book, not an ebook format
	DontReplace     *bool // Do not replace the format if it already exists
}

func (c *Calibre) AddFormatHelp() string {
	if out, err := c.run("add_format", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) AddFormat(opts AddFormatOptions, args ...string) (string, error) {
	argv := []string{"add_format"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Id)
	argv = append(argv, opts.EbookFile)

	// Command Line Options
	// Handling bool
	if opts.AsExtraDataFile != nil && *opts.AsExtraDataFile {
		argv = append(argv, "--as-extra-data-file")
	}
	// Handling bool
	if opts.DontReplace != nil && *opts.DontReplace {
		argv = append(argv, "--dont-replace")
	}
	out, err := c.run(argv...)
	return out, err
}
