// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb add_custom_column [options] label name datatype
//
// Description:
// Create a custom column. label is the machine friendly name of the column. Should
// not contain spaces or colons. name is the human friendly name of the column.
// datatype is one of: bool, comments, composite, datetime, enumeration, float, int, rating, series, text

package calibredb

type AddCustomColumnOptions struct {
	// Command Line Arguments
	Label string  `validate:"required"`
	Name string  `validate:"required"`
	Datatype string  `validate:"required"`

	// Command Line Options
	Display string  // A dictionary of options to customize how the data in this column will be interpreted. This is a JSON  string. For enumeration columns, use --display " {\ " enum_values\ " :[\ " val1\ " , \ " val2\ " ]} " There are many options that can go into the display variable.The options by column type are: composite: composite_template, composite_sort, make_category,contains_html, use_decorations datetime: date_format enumeration: enum_values, enum_colors, use_decorations int, float: number_format text: is_names, use_decorations  The best way to find legal combinations is to create a custom column of the appropriate type in the GUI then look at the backup OPF for a book (ensure that a new OPF has been created since the column was added). You will see the JSON for the " display " for the new column in the OPF.
	IsMultiple *bool  // This column stores tag like data (i.e. multiple comma separated values). Only applies if datatype is text.
}

func (c *Calibre) AddCustomColumnHelp() string {
	return c.run("add_custom_column", "-h")
}

func (c *Calibre) AddCustomColumn(opts AddCustomColumnOptions, args ...string) string {
	return "add_custom_column"
}
