// Code generated by generate.go; DO NOT EDIT.
// %prog add_format [options] id ebook_file
// 
// Add the e-book in ebook_file to the available formats for the logical book identified by id. You can get id by using the search command. If the format already exists, it is replaced, unless the do not replace option is specified.
package calibredb

type AddFormatOptions struct {
	DontReplace bool  // Do not replace the format if it already exists
	AsExtraDataFile bool  // Add the file as an extra data file to the book, not an ebook format
}

func (c *Calibre) AddFormatHelp() string {
	return c.run("add_format", "-h")
}

func (c *Calibre) AddFormat(opts AddFormatOptions, args ...string) string {
	return "add_format"
}
