// Code generated by generate.go; DO NOT EDIT.
// %prog backup_metadata [options]
// 
// Backup the metadata stored in the database into individual OPF files in each
// books folder. This normally happens automatically, but you can run this
// command to force re-generation of the OPF files, with the --all option.
// 
// Note that there is normally no need to do this, as the OPF files are backed up
// automatically, every time metadata is changed.
// 
package calibredb

type BackupMetadataOptions struct {
	All bool  // Normally, this command only operates on books that have out of date OPF files. This option makes it operate on all books.
}

func (c *Calibre) BackupMetadataHelp() string {
	return c.run("backup_metadata", "-h")
}

func (c *Calibre) BackupMetadata(opts BackupMetadataOptions, args ...string) string {
	return "backup_metadata"
}
