// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb backup_metadata [options]
//
// Description:
// Backup the metadata stored in the database into individual OPF files in each
// books folder. This normally happens automatically, but you can run this
// command to force re-generation of the OPF files, with the –all option.

package calibredb

type BackupMetadataOptions struct {

	// Command Line Options
	All *bool  // Normally, this command only operates on books that have out of date OPF files. This option makes it operate on all books.
}

func (c *Calibre) BackupMetadataHelp() string {
	return c.run("backup_metadata", "-h")
}

func (c *Calibre) BackupMetadata(opts BackupMetadataOptions, args ...string) string {
	return "backup_metadata"
}
