// Code generated by generate.go; DO NOT EDIT.
// %prog catalog /path/to/destination.(csv|epub|mobi|xml...) [options]
// 
// Export a catalog in format specified by path/to/destination extension.
// Options control how entries are displayed in the generated catalog output.
// Note that different catalog formats support different sets of options. To
// see the different options, specify the name of the output file and then the
// --help option.
// 
package calibredb

type CatalogOptions struct {
	Ids string  // Comma-separated list of database IDs to catalog. If declared, --search is ignored. Default: all
	Search string  // Filter the results by the search query. For the format of the search query, please see the search-related documentation in the User Manual. Default: no filtering
	Verbose bool  // Show detailed output information. Useful for debugging
}

func (c *Calibre) CatalogHelp() string {
	return c.run("catalog", "-h")
}

func (c *Calibre) Catalog(opts CatalogOptions, args ...string) string {
	return "catalog"
}
