// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb catalog /path/to/destination.(csv|epub|mobi|xml...) [options]
//
// Description:
// Export a catalog in format specified by path/to/destination extension.
// Options control how entries are displayed in the generated catalog output.
// Note that different catalog formats support different sets of options. To
// see the different options, specify the name of the output file and then the
// –help option.

package calibredb

type CatalogOptions struct {
	// Command Line Arguments
	Path string  `validate:"required"`

	// Command Line Options
	Ids string  // Comma-separated list of database IDs to catalog. If declared, --search is ignored. Default: all
	Search string  // Filter the results by the search query. For the format of the search query, please see the search-related documentation in the User Manual. Default: no filtering
	Verbose *bool  // Show detailed output information. Useful for debugging
}

func (c *Calibre) CatalogHelp() string {
	if out, err := c.run("catalog", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) Catalog(opts CatalogOptions, args ...string) (string, error) {
	argv := []string{"catalog"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Path)

	// Command Line Options
	// Handling string
	if opts.Ids != "" {
		argv = append(argv, "--ids", opts.Ids)
	}
	// Handling string
	if opts.Search != "" {
		argv = append(argv, "--search", opts.Search)
	}
	// Handling bool
	if opts.Verbose != nil && *opts.Verbose {
		argv = append(argv, "--verbose")
	}
	out, err := c.run(argv...)
	return out, err
}
