// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb check_library [options]
//
// Description:
// Perform some checks on the filesystem representing a library. Reports are invalid_titles, extra_titles, invalid_authors, extra_authors, missing_formats, extra_formats, extra_files, missing_covers, extra_covers, malformed_formats, malformed_paths, failed_folders

package calibredb

type CheckLibraryOptions struct {

	// Command Line Options
	Csv *bool  // Output in CSV
	IgnoreExtensions string  // Comma-separated list of extensions to ignore. Default: all
	IgnoreNames string  // Comma-separated list of names to ignore. Default: all
	Report string  // Comma-separated list of reports. Default: all
	VacuumFtsDb *bool  // Vacuum the full text search database. This can be very slow and memory intensive, depending on the size of the database.
}

func (c *Calibre) CheckLibraryHelp() string {
	if out, err := c.run("check_library", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) CheckLibrary(opts CheckLibraryOptions, args ...string) (string, error) {
	argv := []string{"check_library"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}

	// Command Line Options
	// Handling bool
	if opts.Csv != nil && *opts.Csv {
		argv = append(argv, "--csv")
	}
	// Handling string
	if opts.IgnoreExtensions != "" {
		argv = append(argv, "--ignore_extensions", opts.IgnoreExtensions)
	}
	// Handling string
	if opts.IgnoreNames != "" {
		argv = append(argv, "--ignore_names", opts.IgnoreNames)
	}
	// Handling string
	if opts.Report != "" {
		argv = append(argv, "--report", opts.Report)
	}
	// Handling bool
	if opts.VacuumFtsDb != nil && *opts.VacuumFtsDb {
		argv = append(argv, "--vacuum-fts-db")
	}
	out, err := c.run(argv...)
	return out, err
}
