// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb check_library [options]
//
// Description:
// Perform some checks on the filesystem representing a library. Reports are invalid_titles, extra_titles, invalid_authors, extra_authors, missing_formats, extra_formats, extra_files, missing_covers, extra_covers, malformed_formats, malformed_paths, failed_folders

package calibredb

type CheckLibraryOptions struct {

	// Command Line Options
	Csv *bool  // Output in CSV
	IgnoreExtensions string  // Comma-separated list of extensions to ignore. Default: all
	IgnoreNames string  // Comma-separated list of names to ignore. Default: all
	Report string  // Comma-separated list of reports. Default: all
	VacuumFtsDb *bool  // Vacuum the full text search database. This can be very slow and memory intensive, depending on the size of the database.
}

func (c *Calibre) CheckLibraryHelp() string {
	return c.run("check_library", "-h")
}

func (c *Calibre) CheckLibrary(opts CheckLibraryOptions, args ...string) string {
	return "check_library"
}
