// Code generated by generate.go; DO NOT EDIT.
// %prog check_library [options]
//
// Perform some checks on the filesystem representing a library. Reports are ', '.join([c[0] for c in CHECKS])
package calibredb

type CheckLibraryOptions struct {
	Csv              bool   // Output in CSV
	Report           string // Comma-separated list of reports. Default: all
	IgnoreExtensions string // Comma-separated list of extensions to ignore. Default: all
	IgnoreNames      string // Comma-separated list of names to ignore. Default: all
	VacuumFtsDb      bool   // Vacuum the full text search database. This can be very slow and memory intensive, depending on the size of the database.
}

func (c *Calibre) CheckLibraryHelp() string {
	return c.run("check_library", "-h")
}

func (c *Calibre) CheckLibrary(opts CheckLibraryOptions, args ...string) string {
	return "check_library"
}
