// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb clone path/to/new/library
//
// Description:
// Create a clone of the current library. This creates a new, empty library that has all the
// same custom columns, Virtual libraries and other settings as the current library.

package calibredb

type CloneOptions struct {
	// Command Line Arguments
	Path string  `validate:"required"`
}

func (c *Calibre) CloneHelp() string {
	return c.run("clone", "-h")
}

func (c *Calibre) Clone(opts CloneOptions, args ...string) string {
	return "clone"
}
