// Code generated by generate.go; DO NOT EDIT.
// %prog clone path/to/new/library
// 
// Create a clone of the current library. This creates a new, empty library that has all the
// same custom columns, Virtual libraries and other settings as the current library.
// 
// The cloned library will contain no books. If you want to create a full duplicate, including
// all books, then simply use your filesystem tools to copy the library folder.
//     
package calibredb

type CloneOptions struct {
}

func (c *Calibre) CloneHelp() string {
	return c.run("clone", "-h")
}

func (c *Calibre) Clone(opts CloneOptions, args ...string) string {
	return "clone"
}
