// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb clone path/to/new/library
//
// Description:
// Create a clone of the current library. This creates a new, empty library that has all the
// same custom columns, Virtual libraries and other settings as the current library.

package calibredb

type CloneOptions struct {
	// Command Line Arguments
	Path string  `validate:"required"`
}

func (c *Calibre) CloneHelp() string {
	if out, err := c.run("clone", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) Clone(opts CloneOptions, args ...string) (string, error) {
	argv := []string{"clone"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Path)
	out, err := c.run(argv...)
	return out, err
}
