// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb custom_columns [options]
//
// Description:
// List available custom columns. Shows column labels and ids.

package calibredb

type CustomColumnsOptions struct {

	// Command Line Options
	Details *bool  // Show details for each column.
}

func (c *Calibre) CustomColumnsHelp() string {
	return c.run("custom_columns", "-h")
}

func (c *Calibre) CustomColumns(opts CustomColumnsOptions, args ...string) string {
	return "custom_columns"
}
