// Code generated by generate.go; DO NOT EDIT.
// %prog custom_columns [options]
// 
// List available custom columns. Shows column labels and ids.
//     
package calibredb

type CustomColumnsOptions struct {
	Details bool  // Show details for each column.
}

func (c *Calibre) CustomColumnsHelp() string {
	return c.run("custom_columns", "-h")
}

func (c *Calibre) CustomColumns(opts CustomColumnsOptions, args ...string) string {
	return "custom_columns"
}
