// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb custom_columns [options]
//
// Description:
// List available custom columns. Shows column labels and ids.

package calibredb

type CustomColumnsOptions struct {

	// Command Line Options
	Details *bool  // Show details for each column.
}

func (c *Calibre) CustomColumnsHelp() string {
	if out, err := c.run("custom_columns", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) CustomColumns(opts CustomColumnsOptions, args ...string) (string, error) {
	argv := []string{"custom_columns"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	out, err := c.run(argv...)
	return out, err
}
