// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb embed_metadata [options] book_id
//
// Description:
// Update the metadata in the actual book files stored in the calibre library from
// the metadata in the calibre database.  Normally, metadata is updated only when
// exporting files from calibre, this command is useful if you want the files to
// be updated in place. Note that different file formats support different amounts
// of metadata. You can use the special value ‘all’ for book_id to update metadata
// in all books. You can also specify many book ids separated by spaces and id ranges
// separated by hyphens. For example: calibredb embed_metadata 1 2 10-15 23

package calibredb

type EmbedMetadataOptions struct {
	// Command Line Arguments
	BookId string  `validate:"required"`

	// Command Line Options
	OnlyFormats string  // Only update metadata in files of the specified format. Specify it multiple times for multiple formats. By default, all formats are updated.
}

func (c *Calibre) EmbedMetadataHelp() string {
	return c.run("embed_metadata", "-h")
}

func (c *Calibre) EmbedMetadata(opts EmbedMetadataOptions, args ...string) string {
	return "embed_metadata"
}
