// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb export [options] ids
//
// Description:
// Export the books specified by ids (a comma separated list) to the filesystem.
// The export operation saves all formats of the book, its cover and metadata (in
// an OPF file). Any extra data files associated with the book are also saved.
// You can get id numbers from the search command.

package calibredb

type ExportOptions struct {
	// Command Line Arguments
	Ids []string `validate:"required"`

	// Command Line Options
	All       *bool  // Export all books in database, ignoring the list of ids.
	Progress  *bool  // Report progress
	SingleDir *bool  // Export all books into a single folder
	ToDir     string // Export books to the specified folder. Default is .
}

func (c *Calibre) ExportHelp() string {
	if out, err := c.run("export", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) Export(opts ExportOptions, args ...string) (string, error) {
	argv := []string{"export"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Ids...)

	// Command Line Options
	// Handling bool
	if opts.All != nil && *opts.All {
		argv = append(argv, "--all")
	}
	// Handling bool
	if opts.Progress != nil && *opts.Progress {
		argv = append(argv, "--progress")
	}
	// Handling bool
	if opts.SingleDir != nil && *opts.SingleDir {
		argv = append(argv, "--single-dir")
	}
	// Handling string
	if opts.ToDir != "" {
		argv = append(argv, "--to-dir", opts.ToDir)
	}
	out, err := c.run(argv...)
	return out, err
}
