// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb export [options] ids
//
// Description:
// Export the books specified by ids (a comma separated list) to the filesystem.
// The export operation saves all formats of the book, its cover and metadata (in
// an OPF file). Any extra data files associated with the book are also saved.
// You can get id numbers from the search command.

package calibredb

type ExportOptions struct {
	// Command Line Arguments
	Ids []string  `validate:"required"`

	// Command Line Options
	All *bool  // Export all books in database, ignoring the list of ids.
	Progress *bool  // Report progress
	SingleDir *bool  // Export all books into a single folder
	ToDir string  // Export books to the specified folder. Default is .
}

func (c *Calibre) ExportHelp() string {
	return c.run("export", "-h")
}

func (c *Calibre) Export(opts ExportOptions, args ...string) string {
	return "export"
}
