// Code generated by generate.go; DO NOT EDIT.
// %prog fts_index [options] {enable}/{disable}/{status}/{reindex}
// 
// Control the Full text search indexing process.
// 
// {enable}
//     Turns on FTS indexing for this library
// {disable}
//     Turns off FTS indexing for this library
// {status}
//     Shows the current indexing status
// {reindex}
//     Can be used to re-index either particular books or
//     the entire library. To re-index particular books
//     specify the book ids as additional arguments after the
//     {reindex} command. If no book ids are specified the
//     entire library is re-indexed.
//  (format args: [])
package calibredb

type FtsIndexOptions struct {
	WaitForCompletion bool  // Wait till all books are indexed, showing indexing progress periodically
	IndexingSpeed string  // The speed of indexing. Use fast for fast indexing using all your computers resources and slow for less resource intensive indexing. Note that the speed is reset to slow after every invocation.
}

func (c *Calibre) FtsIndexHelp() string {
	return c.run("fts_index", "-h")
}

func (c *Calibre) FtsIndex(opts FtsIndexOptions, args ...string) string {
	return "fts_index"
}
