// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb fts_index [options] enable/disable/status/reindex
//
// Description:
// Control the Full text search indexing process.

package calibredb

type FtsIndexOptions struct {
	// Command Line Arguments
	EnableDisableStatusReindex string  `validate:"required"`

	// Command Line Options
	IndexingSpeed IndexingSpeedChoice  // The speed of indexing. Use fast for fast indexing using all your computers resources and slow for less resource intensive indexing. Note that the speed is reset to slow after every invocation.
	WaitForCompletion *bool  // Wait till all books are indexed, showing indexing progress periodically
}

type IndexingSpeedChoice string

const (
	Fast IndexingSpeedChoice = "fast"
	Slow IndexingSpeedChoice = "slow"
)

func (c *Calibre) FtsIndexHelp() string {
	if out, err := c.run("fts_index", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) FtsIndex(opts FtsIndexOptions, args ...string) (string, error) {
	argv := []string{"fts_index"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.EnableDisableStatusReindex)

	// Command Line Options
	// Handling other choice
	// Handling bool
	if opts.WaitForCompletion != nil && *opts.WaitForCompletion {
		argv = append(argv, "--wait-for-completion")
	}
	out, err := c.run(argv...)
	return out, err
}
