// Code generated by generate.go; DO NOT EDIT.
// %prog fts_search [options] search expression
// 
// Do a full text search on the entire library or a subset of it.
// 
// 
package calibredb

type FtsSearchOptions struct {
	IncludeSnippets bool  // Include snippets of the text surrounding each match. Note that this makes searching much slower.
	MatchStartMarker string  // The marker used to indicate the start of a matched word inside a snippet
	MatchEndMarker string  // The marker used to indicate the end of a matched word inside a snippet
	DoNotMatchOnRelatedWords bool  // Only match on exact words not related words. So correction will not match correcting.
	RestrictTo string  // Restrict the searched books, either using a search expression or ids. For example: ids:1,2,3 to restrict by ids or search:tag:foo to restrict to books having the tag foo.
	OutputFormat string  // The format to output the search results in. Either "text" for plain text or "json" for JSON output.
	IndexingThreshold float64  // How much of the library must be indexed before searching is allowed, as a percentage. Defaults to 90
}

func (c *Calibre) FtsSearchHelp() string {
	return c.run("fts_search", "-h")
}

func (c *Calibre) FtsSearch(opts FtsSearchOptions, args ...string) string {
	return "fts_search"
}
