// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb list_categories [options]
//
// Description:
// Produce a report of the category information in the database. The
// information is the equivalent of what is shown in the Tag browser.

package calibredb

type ListCategoriesOptions struct {

	// Command Line Options
	Categories string  // Comma-separated list of category lookup names. Default: all
	Csv *bool  // Output in CSV
	Dialect DialectChoice  // The type of CSV file to produce. Choices: excel, excel-tab, unix
	ItemCount *bool  // Output only the number of items in a category instead of the counts per item within the category
	Width int  // The maximum width of a single line in the output. Defaults to detecting screen size.
}

type DialectChoice string

const (
	CsvListDialects DialectChoice = "csv.list_dialects"
)

func (c *Calibre) ListCategoriesHelp() string {
	if out, err := c.run("list_categories", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) ListCategories(opts ListCategoriesOptions, args ...string) (string, error) {
	argv := []string{"list_categories"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	out, err := c.run(argv...)
	return out, err
}
