// Code generated by generate.go; DO NOT EDIT.
// %prog list_categories [options]
// 
// Produce a report of the category information in the database. The
// information is the equivalent of what is shown in the Tag browser.
// 
package calibredb

type ListCategoriesOptions struct {
	ItemCount bool  // Output only the number of items in a category instead of the counts per item within the category
	Csv bool  // Output in CSV
	Dialect string  // The type of CSV file to produce. Choices: ', '.join(sorted(csv.list_dialects()))
	Categories string  // Comma-separated list of category lookup names. Default: all
	Width int  // The maximum width of a single line in the output. Defaults to detecting screen size.
}

func (c *Calibre) ListCategoriesHelp() string {
	return c.run("list_categories", "-h")
}

func (c *Calibre) ListCategories(opts ListCategoriesOptions, args ...string) string {
	return "list_categories"
}
