// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb remove ids
//
// Description:
// Remove the books identified by ids from the database. ids should be a comma separated list of id numbers (you can get id numbers by using the search command). For example, 23,34,57-85 (when specifying a range, the last number in the range is not included).

package calibredb

type RemoveOptions struct {
	// Command Line Arguments
	Ids []string  `validate:"required"`

	// Command Line Options
	Permanent *bool  // Do not use the Recycle Bin
}

func (c *Calibre) RemoveHelp() string {
	return c.run("remove", "-h")
}

func (c *Calibre) Remove(opts RemoveOptions, args ...string) string {
	return "remove"
}
