// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb remove_custom_column [options] label
//
// Description:
// Remove the custom column identified by label. You can see available
// columns with the custom_columns command.

package calibredb

type RemoveCustomColumnOptions struct {
	// Command Line Arguments
	Label string `validate:"required"`

	// Command Line Options
	Force *bool // Do not ask for confirmation
}

func (c *Calibre) RemoveCustomColumnHelp() string {
	if out, err := c.run("remove_custom_column", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) RemoveCustomColumn(opts RemoveCustomColumnOptions, args ...string) (string, error) {
	argv := []string{"remove_custom_column"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Label)

	// Command Line Options
	// Handling bool
	if opts.Force != nil && *opts.Force {
		argv = append(argv, "--force")
	}
	out, err := c.run(argv...)
	return out, err
}
