// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb remove_custom_column [options] label
//
// Description:
// Remove the custom column identified by label. You can see available
// columns with the custom_columns command.

package calibredb

type RemoveCustomColumnOptions struct {
	// Command Line Arguments
	Label string  `validate:"required"`

	// Command Line Options
	Force *bool  // Do not ask for confirmation
}

func (c *Calibre) RemoveCustomColumnHelp() string {
	return c.run("remove_custom_column", "-h")
}

func (c *Calibre) RemoveCustomColumn(opts RemoveCustomColumnOptions, args ...string) string {
	return "remove_custom_column"
}
