// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb remove_format [options] id fmt
//
// Description:
// Remove the format fmt from the logical book identified by id. You can get id by using the search command. fmt should be a file extension like LRF or TXT or EPUB. If the logical book does not have fmt available, do nothing.

package calibredb

type RemoveFormatOptions struct {
	// Command Line Arguments
	Id  string `validate:"required"`
	Fmt string `validate:"required"`
}

func (c *Calibre) RemoveFormatHelp() string {
	if out, err := c.run("remove_format", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) RemoveFormat(opts RemoveFormatOptions, args ...string) (string, error) {
	argv := []string{"remove_format"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Id)
	argv = append(argv, opts.Fmt)
	out, err := c.run(argv...)
	return out, err
}
