// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb remove ids
//
// Description:
// Remove the books identified by ids from the database. ids should be a comma separated list of id numbers (you can get id numbers by using the search command). For example, 23,34,57-85 (when specifying a range, the last number in the range is not included).

package calibredb

type RemoveOptions struct {
	// Command Line Arguments
	Ids []string  `validate:"required"`

	// Command Line Options
	Permanent *bool  // Do not use the Recycle Bin
}

func (c *Calibre) RemoveHelp() string {
	if out, err := c.run("remove", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) Remove(opts RemoveOptions, args ...string) (string, error) {
	argv := []string{"remove"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Ids...)

	// Command Line Options
	// Handling bool
	if opts.Permanent != nil && *opts.Permanent {
		argv = append(argv, "--permanent")
	}
	out, err := c.run(argv...)
	return out, err
}
