// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb remove_format [options] id fmt
//
// Description:
// Remove the format fmt from the logical book identified by id. You can get id by using the search command. fmt should be a file extension like LRF or TXT or EPUB. If the logical book does not have fmt available, do nothing.

package calibredb

type RemoveFormatOptions struct {
	// Command Line Arguments
	Id string  `validate:"required"`
	Fmt string  `validate:"required"`
}

func (c *Calibre) RemoveFormatHelp() string {
	return c.run("remove_format", "-h")
}

func (c *Calibre) RemoveFormat(opts RemoveFormatOptions, args ...string) string {
	return "remove_format"
}
