// Code generated by generate.go; DO NOT EDIT.
// %prog restore_database [options]
// 
// Restore this database from the metadata stored in OPF files in each
// folder of the calibre library. This is useful if your metadata.db file
// has been corrupted.
// 
// WARNING: This command completely regenerates your database. You will lose
// all saved searches, user categories, plugboards, stored per-book conversion
// settings, and custom recipes. Restored metadata will only be as accurate as
// what is found in the OPF files.
//     
package calibredb

type RestoreDatabaseOptions struct {
	ReallyDoIt bool  // Really do the recovery. The command will not run unless this option is specified.
}

func (c *Calibre) RestoreDatabaseHelp() string {
	return c.run("restore_database", "-h")
}

func (c *Calibre) RestoreDatabase(opts RestoreDatabaseOptions, args ...string) string {
	return "restore_database"
}
