// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb restore_database [options]
//
// Description:
// Restore this database from the metadata stored in OPF files in each
// folder of the calibre library. This is useful if your metadata.db file
// has been corrupted.

package calibredb

type RestoreDatabaseOptions struct {

	// Command Line Options
	ReallyDoIt *bool  // Really do the recovery. The command will not run unless this option is specified.
}

func (c *Calibre) RestoreDatabaseHelp() string {
	return c.run("restore_database", "-h")
}

func (c *Calibre) RestoreDatabase(opts RestoreDatabaseOptions, args ...string) string {
	return "restore_database"
}
