// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb restore_database [options]
//
// Description:
// Restore this database from the metadata stored in OPF files in each
// folder of the calibre library. This is useful if your metadata.db file
// has been corrupted.

package calibredb

type RestoreDatabaseOptions struct {

	// Command Line Options
	ReallyDoIt *bool // Really do the recovery. The command will not run unless this option is specified.
}

func (c *Calibre) RestoreDatabaseHelp() string {
	if out, err := c.run("restore_database", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) RestoreDatabase(opts RestoreDatabaseOptions, args ...string) (string, error) {
	argv := []string{"restore_database"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}

	// Command Line Options
	// Handling bool
	if opts.ReallyDoIt != nil && *opts.ReallyDoIt {
		argv = append(argv, "--really-do-it")
	}
	out, err := c.run(argv...)
	return out, err
}
