// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb saved_searches [options] (list|add|remove)
//
// Description:
// Manage the saved searches stored in this database.
// If you try to add a query with a name that already exists, it will be
// replaced.

package calibredb

type SavedSearchesOptions struct {
}

func (c *Calibre) SavedSearchesHelp() string {
	if out, err := c.run("saved_searches", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) SavedSearches(opts SavedSearchesOptions, args ...string) (string, error) {
	argv := []string{"saved_searches"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	out, err := c.run(argv...)
	return out, err
}
