// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb saved_searches [options] (list|add|remove)
//
// Description:
// Manage the saved searches stored in this database.
// If you try to add a query with a name that already exists, it will be
// replaced.

package calibredb

type SavedSearchesOptions struct {
}

func (c *Calibre) SavedSearchesHelp() string {
	return c.run("saved_searches", "-h")
}

func (c *Calibre) SavedSearches(opts SavedSearchesOptions, args ...string) string {
	return "saved_searches"
}
