// Code generated by generate.go; DO NOT EDIT.
// %prog saved_searches [options] (list|add|remove)
// 
// Manage the saved searches stored in this database.
// If you try to add a query with a name that already exists, it will be
// replaced.
// 
// Syntax for adding:
// 
// %prog saved_searches add search_name search_expression
// 
// Syntax for removing:
// 
// %prog saved_searches remove search_name
//     
package calibredb

type SavedSearchesOptions struct {
}

func (c *Calibre) SavedSearchesHelp() string {
	return c.run("saved_searches", "-h")
}

func (c *Calibre) SavedSearches(opts SavedSearchesOptions, args ...string) string {
	return "saved_searches"
}
