// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb search [options] search expression
//
// Description:
// Search the library for the specified search term, returning a comma separated
// list of book ids matching the search expression. The output format is useful
// to feed into other commands that accept a list of ids as input.

package calibredb

type SearchOptions struct {
	// Command Line Arguments
	Search string  `validate:"required"`
	Expression string  `validate:"required"`

	// Command Line Options
	Limit int  // The maximum number of results to return. Default is all results.
}

func (c *Calibre) SearchHelp() string {
	return c.run("search", "-h")
}

func (c *Calibre) Search(opts SearchOptions, args ...string) string {
	return "search"
}
