// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb search [options] search expression
//
// Description:
// Search the library for the specified search term, returning a comma separated
// list of book ids matching the search expression. The output format is useful
// to feed into other commands that accept a list of ids as input.

package calibredb

import (
	"fmt"
)

type SearchOptions struct {
	// Command Line Arguments
	Search     string `validate:"required"`
	Expression string `validate:"required"`

	// Command Line Options
	Limit int // The maximum number of results to return. Default is all results.
}

func (c *Calibre) SearchHelp() string {
	if out, err := c.run("search", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) Search(opts SearchOptions, args ...string) (string, error) {
	argv := []string{"search"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Search)
	argv = append(argv, opts.Expression)

	// Command Line Options
	// Handling int
	if opts.Limit != 0 {
		argv = append(argv, "--limit", fmt.Sprint(opts.Limit))
	}
	out, err := c.run(argv...)
	return out, err
}
