// Code generated by generate.go; DO NOT EDIT.
// %prog search [options] search expression
// 
// Search the library for the specified search term, returning a comma separated
// list of book ids matching the search expression. The output format is useful
// to feed into other commands that accept a list of ids as input.
// 
// The search expression can be anything from calibre's powerful search query
// language, for example: %prog search author:asimov 'title:"i robot"'
// 
package calibredb

type SearchOptions struct {
	Limit int  // The maximum number of results to return. Default is all results.
}

func (c *Calibre) SearchHelp() string {
	return c.run("search", "-h")
}

func (c *Calibre) Search(opts SearchOptions, args ...string) string {
	return "search"
}
