// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb set_custom [options] column id value
//
// Description:
// Set the value of a custom column for the book identified by id.
// You can get a list of ids using the search command.
// You can get a list of custom column names using the custom_columns
// command.

package calibredb

type SetCustomOptions struct {
	// Command Line Arguments
	Column string  `validate:"required"`
	Id string  `validate:"required"`
	Value string  `validate:"required"`

	// Command Line Options
	Append *bool  // If the column stores multiple values, append the specified values to the existing ones, instead of replacing them.
}

func (c *Calibre) SetCustomHelp() string {
	return c.run("set_custom", "-h")
}

func (c *Calibre) SetCustom(opts SetCustomOptions, args ...string) string {
	return "set_custom"
}
