// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb set_metadata [options] book_id [/path/to/metadata.opf]
//
// Description:
// Set the metadata stored in the calibre database for the book identified by
// book_id from the OPF file metadata.opf. book_id is a book id number from the
// search command. You can get a quick feel for the OPF format by using the
// –as-opf switch to the show_metadata command. You can also set the metadata of
// individual fields with the –field option. If you use the –field option, there
// is no need to specify an OPF file.

package calibredb

type SetMetadataOptions struct {
	// Command Line Arguments
	BookId string  `validate:"required"`
	Path string  `validate:"required"`

	// Command Line Options
	Field []string  // The field to set. Format is field_name:value, for example: --field tags:tag1,tag2. Use --list-fields to get a list of all field names. You can specify this option multiple times to set multiple fields. Note: For languages you must use the ISO639 language codes (e.g. en for English, fr for French and so on). For identifiers, the syntax is --field identifiers:isbn:XXXX,doi:YYYYY. For boolean (yes/no) fields use true and false or yes and no.
	ListFields *bool  // List the metadata field names that can be used with the --field option
}

func (c *Calibre) SetMetadataHelp() string {
	if out, err := c.run("set_metadata", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) SetMetadata(opts SetMetadataOptions, args ...string) (string, error) {
	argv := []string{"set_metadata"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.BookId)
	argv = append(argv, opts.Path)

	// Command Line Options
	// Handling []string
	if len(opts.Field) > 0 {
		argv = append(argv, "--field")
		argv = append(argv, opts.Field...)
	}
	// Handling bool
	if opts.ListFields != nil && *opts.ListFields {
		argv = append(argv, "--list-fields")
	}
	out, err := c.run(argv...)
	return out, err
}
