// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb show_metadata [options] id
//
// Description:
// Show the metadata stored in the calibre database for the book identified by id.
// id is an id number from the search command.

package calibredb

type ShowMetadataOptions struct {
	// Command Line Arguments
	Id string  `validate:"required"`

	// Command Line Options
	AsOpf *bool  // Print metadata in OPF form (XML)
}

func (c *Calibre) ShowMetadataHelp() string {
	return c.run("show_metadata", "-h")
}

func (c *Calibre) ShowMetadata(opts ShowMetadataOptions, args ...string) string {
	return "show_metadata"
}
