// Code generated by generate.go; DO NOT EDIT.
// 
// %prog show_metadata [options] id
// 
// Show the metadata stored in the calibre database for the book identified by id.
// id is an id number from the search command.
// 
package calibredb

type ShowMetadataOptions struct {
	AsOpf bool  // Print metadata in OPF form (XML)
}

func (c *Calibre) ShowMetadataHelp() string {
	return c.run("show_metadata", "-h")
}

func (c *Calibre) ShowMetadata(opts ShowMetadataOptions, args ...string) string {
	return "show_metadata"
}
