// Code generated by generate.go; DO NOT EDIT.
//
// Command:
// calibredb show_metadata [options] id
//
// Description:
// Show the metadata stored in the calibre database for the book identified by id.
// id is an id number from the search command.

package calibredb

type ShowMetadataOptions struct {
	// Command Line Arguments
	Id string `validate:"required"`

	// Command Line Options
	AsOpf *bool // Print metadata in OPF form (XML)
}

func (c *Calibre) ShowMetadataHelp() string {
	if out, err := c.run("show_metadata", "-h"); err != nil {
		return err.Error()
	} else {
		return out
	}
}

func (c *Calibre) ShowMetadata(opts ShowMetadataOptions, args ...string) (string, error) {
	argv := []string{"show_metadata"}

	// validate the command line arguments
	err := c.validate.Struct(opts)
	if err != nil {
		return "", err
	}
	// Command Line Arguments
	argv = append(argv, opts.Id)

	// Command Line Options
	// Handling bool
	if opts.AsOpf != nil && *opts.AsOpf {
		argv = append(argv, "--as-opf")
	}
	out, err := c.run(argv...)
	return out, err
}
